title: Zachary Salloum — Portfolio
description: Mechanical engineering portfolio

# ---- fill these in ----
resume_url: /assets/Zachary_Salloum.pdf
linkedin_url: https://www.linkedin.com/in/zachsalloum/
email: zachsall7@gmail.com

nav_links:
  - label: ABOUT
    url: "#about"
  - label: "PRJ 1 — OUTBOARD"
    url: "#prj-1"
  - label: "PRJ 2 — 3D PRINTER"
    url: "#prj-2"

markdown: kramdown
